import type { Command } from '@sapphire/framework';
import { resolveKey } from '@sapphire/plugin-i18next';
import { LanguageKeys } from '#lib/i18n/languageKeys';
import type { Labels } from './types';

export async function resolveLabels(interaction: Command.ChatInputCommandInteraction): Promise<Labels> {
	const [
		yes,
		no,
		none,
		defaultMsg,
		langEnUS,
		langFrFR,
		sortMonth,
		sortUpcoming,
		viewTitle,
		secGeneral,
		secAnnouncements,
		secBirthdayRole,
		secOverviewLogs,
		lTimezone,
		lLanguage,
		lOverviewSort,
		lActive,
		lPremium,
		lAnnChannel,
		lAnnMessage,
		lPingRole,
		lBirthdayRole,
		lOverviewChannel,
		lLogChannel,
		btnGeneral,
		btnAnnouncements,
		btnBirthdayRole,
		btnOverviewLogs,
		btnBack,
		btnPremium,
		editGeneralTitle,
		editAnnouncementsTitle,
		editBirthdayRoleTitle,
		editOverviewLogsTitle,
		editPremiumTitle,
		plhLang,
		plhSort,
		plhAnnChannel,
		plhPingRole,
		plhBirthdayRole,
		plhOverviewChannel,
		plhLogChannel,
		msgBtnLabel,
		msgModalTitle,
		msgModalLabel,
		plhTimezoneRegion,
		plhTimezone,
		removeChannel,
		removeRole,
		pmActivateHere,
		pmDeactivateHere,
		pmSlotsLabel,
		pmServersLabel,
		pmNotPatron,
		pmNotPatronDescription,
		pmPatreonButton
	] = await Promise.all([
		resolveKey(interaction, LanguageKeys.Globals.Yes),
		resolveKey(interaction, LanguageKeys.Globals.No),
		resolveKey(interaction, LanguageKeys.Globals.None),
		resolveKey(interaction, LanguageKeys.Commands.Config.DefaultAnnouncementMessage),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandLanguageOptionLanguageChoiceEnUS),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandLanguageOptionLanguageChoiceFrFR),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandOverviewSortOptionSortChoiceMonth),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandOverviewSortOptionSortChoiceUpcoming),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewResponseTitle),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewSectionGeneral),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewSectionAnnouncements),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewSectionBirthdayRole),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewSectionOverviewAndLogs),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelTimezone),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelLanguage),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelOverviewSort),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelActive),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelPremium),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelAnnouncementChannel),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelAnnouncementMessage),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelBirthdayPingRole),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelBirthdayRole),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelOverviewChannel),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewLabelLogChannel),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewButtonGeneral),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewButtonAnnouncements),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewButtonBirthdayRole),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewButtonOverviewAndLogs),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewButtonBack),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewButtonPremium),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditGeneralTitle),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditAnnouncementsTitle),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditBirthdayRoleTitle),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditOverviewAndLogsTitle),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditPremiumTitle),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectLanguagePlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectSortPlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectChannelPlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectPingRolePlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectRolePlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectOverviewChannelPlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectLogChannelPlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditModalMessageButtonLabel),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditModalMessageTitle),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditModalMessageLabel),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectTimezoneRegionPlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditSelectTimezonePlaceholder),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditRemoveChannel),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditRemoveRole),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditPremiumActivateHere),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditPremiumDeactivateHere),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditPremiumSlotsLabel),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditPremiumServersLabel),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditPremiumNotPatron),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditPremiumNotPatronDescription),
		resolveKey(interaction, LanguageKeys.Commands.Config.SubcommandViewEditPremiumPatreonButton)
	]);

	return {
		yes,
		no,
		none,
		defaultMsg,
		langEnUS,
		langFrFR,
		sortMonth,
		sortUpcoming,
		viewTitle,
		secGeneral,
		secAnnouncements,
		secBirthdayRole,
		secOverviewLogs,
		lTimezone,
		lLanguage,
		lOverviewSort,
		lActive,
		lPremium,
		lAnnChannel,
		lAnnMessage,
		lPingRole,
		lBirthdayRole,
		lOverviewChannel,
		lLogChannel,
		btnGeneral,
		btnAnnouncements,
		btnBirthdayRole,
		btnOverviewLogs,
		btnBack,
		btnPremium,
		editGeneralTitle,
		editAnnouncementsTitle,
		editBirthdayRoleTitle,
		editOverviewLogsTitle,
		editPremiumTitle,
		plhLang,
		plhSort,
		plhAnnChannel,
		plhPingRole,
		plhBirthdayRole,
		plhOverviewChannel,
		plhLogChannel,
		msgBtnLabel,
		msgModalTitle,
		msgModalLabel,
		plhTimezoneRegion,
		plhTimezone,
		removeChannel,
		removeRole,
		pmActivateHere,
		pmDeactivateHere,
		pmSlotsLabel,
		pmServersLabel,
		pmNotPatron,
		pmNotPatronDescription,
		pmPatreonButton
	};
}
